name: LinktreeCI
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test project
        run: npm run test:run
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build application
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: Deploy on GH actions
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
      